### ISSUE TITLE
Bug in day of month

### ISSUE THREAD

**Issue by mykhailobez** [anushaihalapathirana/cron-expression-validator#1]
Hi,

I am using your library and I am pretty happy with it. Thanks a million!

But there is a bug in validating quartz cron like this:
`0 * * 10,30 * ? *`
The parser returns an error because the valid numbers for `dayOfMonth` are from 1 to 12 (when days are specified using `,`). But there should actually be from 1 to 31.

- I guess the problem is here: 

https://github.com/anushaihalapathirana/cron-expression-validator/blob/9a0e15cc41ed80611acc85f4339c35f2647ed4d6/index.js#L184

- And there:

https://github.com/anushaihalapathirana/cron-expression-validator/blob/9a0e15cc41ed80611acc85f4339c35f2647ed4d6/index.js#L188

**Comment by anushaihalapathirana** [comment]
Hi,

Thank you for using my library and reporting the issue. I fixed the issue and please update to the latest version (1.0.17)
