### ISSUE TITLE
'Day of month' and 'Day of week' should support 'C'

### ISSUE THREAD

**Issue by HuangWeiping007** [anushaihalapathirana/cron-expression-validator#13]
'Day of month' and 'Day of week' should support 'C'

For cron expression rules, please refer to the following webpage address:
https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm

**Comment by anushaihalapathirana** [comment]
Hi,

This library currently supports only cron expressions supported by the Quartz job scheduling library.

http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html
