### ISSUE TITLE
Library does not work on IE11 due to four instances of arrow functions

### ISSUE THREAD

**Issue by joel-stewart** [anushaihalapathirana/cron-expression-validator#5]
The plugin does not currently work on IE11 and causes the application to break. This is because of the usage of a few arrow functions in the source code. If these were replaced with normal functions everything would work fine.

**Comment by anushaihalapathirana** [comment]
issue is fixed with https://github.com/anushaihalapathirana/cron-expression-validator/pull/6

**Comment by joel-stewart** [comment]
Thanks heaps @anushaihalapathirana !

I'll wait for the next release, thank you also for the library!

**Comment by anushaihalapathirana** [comment]
Hi,

Thank you for the contribution. I update the package. (Latest version
1.0.18)

Regards,
Anusha Ihalapathirana

0714652025
